"""python-for-android recipe: shiboken6, with its two native libraries rebuilt.

Copied by scripts/build-apk over the recipe pyside6-android-deploy generates
(phase 1f), with @WHEEL_SHIBOKEN@ and @PYSIDE_VERSION@ filled in. The generated
recipe unzips Qt's prebuilt wheel and nothing else; this one does the same and
then replaces exactly two files in it.

Why: Google Play rejects any 64-bit native library whose ELF LOAD segments are
aligned to less than 16 KB (the Android 15 page-size requirement, enforced for
every upload since November 2025). Qt's own libraries in the PySide6 Android
wheel are 16 KB-aligned. The two in the shiboken6 wheel are not:

    shiboken6/libshiboken6.abi3.so   p_align 0x1000
    shiboken6/Shiboken.abi3.so       p_align 0x1000

— in 6.11.0, 6.11.1 and 6.11.2 alike. It cannot be patched in the header: the
segments were laid out for 4 KB pages and share 16 KB pages, so only a relink
fixes it, and a relink needs the objects. So this builds both from the matching
pyside-setup source release, with the same NDK (r27c) and the same API level
(35, read from the original's .note.android.ident) Qt used, plus
-z max-page-size=16384.

libpyside6 and every Qt*.abi3.so binding link against libshiboken6, so the
rebuild must be ABI-identical. build_arch() refuses to install it unless it
exports every dynamic symbol the original did, has the same SONAME, NEEDED and
RUNPATH, and is 16 KB-aligned. Checked on the first build: 448 of 448 symbols,
none missing, none extra.

Nothing here needs Qt for Android. libshiboken is plain C++ against the Python
C API; the one Qt-shaped thing in the configure step is a vestigial
`find_package(Qt6 COMPONENTS Core)` in ShibokenSetup.cmake, satisfied by a stub
(see _write_qt6_stub). The Shiboken module's wrapper source is generated by the
*host* shiboken6 generator — nixpkgs' python3Packages.shiboken6-generator, the
same 6.11.0, exported by flake.nix as SHIBOKEN6_HOST_PATH.
"""

from __future__ import annotations

import os
import shutil
import struct
import sys
import zipfile
from pathlib import Path

import sh

from pythonforandroid.logger import info, shprint
from pythonforandroid.recipe import PythonRecipe
from pythonforandroid.util import BuildInterruptingException, current_directory

PAGE_16K = 0x4000

#: The API level Qt built the original wheel's shiboken at: 0x23 in its
#: .note.android.ident. PySide's own bindings are built at 35 too. Matching it
#: keeps the rebuild's imports identical — at 28 the NDK switches to emulated
#: TLS and the library grows an import of __emutls_get_address the original
#: never had. Every symbol the PySide wheel imports exists at API 28 as well,
#: which is what lets the app's minSdk stay at 28.
TARGET_API = 35


# --- A minimal ELF64 reader ---------------------------------------------------
#
# Enough to compare two shared objects: LOAD alignment, the dynamic tags that
# decide how the loader finds dependencies, and the exported symbol names. Pure
# Python so the check does not depend on which readelf happens to be on PATH.

PT_LOAD, PT_DYNAMIC = 1, 2
DT_NULL, DT_NEEDED, DT_STRTAB, DT_SONAME, DT_RUNPATH = 0, 1, 5, 14, 29
SHT_DYNSYM = 11


def _cstr(blob: bytes, offset: int) -> str:
    return blob[offset:blob.index(b"\0", offset)].decode()


def elf_info(path: Path) -> dict:
    b = path.read_bytes()
    if b[:4] != b"\x7fELF" or b[4] != 2:
        raise ValueError(f"{path} is not a 64-bit ELF")
    e_phoff, e_shoff = struct.unpack_from("<QQ", b, 0x20)
    e_phentsize, e_phnum, e_shentsize, e_shnum = struct.unpack_from("<HHHH", b, 0x36)

    aligns, dynamic = [], None
    for i in range(e_phnum):
        p_type, _, p_offset, p_vaddr, _, p_filesz, _, p_align = struct.unpack_from(
            "<IIQQQQQQ", b, e_phoff + i * e_phentsize)
        if p_type == PT_LOAD:
            aligns.append(p_align)
        elif p_type == PT_DYNAMIC:
            dynamic = (p_offset, p_filesz)

    # Section headers give the .dynsym and its string table directly.
    sections = [struct.unpack_from("<IIQQQQIIQQ", b, e_shoff + i * e_shentsize)
                for i in range(e_shnum)]
    exported = set()
    for _, sh_type, _, _, sh_offset, sh_size, sh_link, _, _, sh_entsize in sections:
        if sh_type != SHT_DYNSYM:
            continue
        strtab_off = sections[sh_link][4]
        for j in range(1, sh_size // sh_entsize):
            st_name, st_info, _, st_shndx = struct.unpack_from(
                "<IBBH", b, sh_offset + j * sh_entsize)
            binding = st_info >> 4                    # 1 GLOBAL, 2 WEAK
            if st_shndx != 0 and binding in (1, 2):   # defined here, visible
                exported.add(_cstr(b, strtab_off + st_name))

    tags = []
    if dynamic:
        off, size = dynamic
        entries = [struct.unpack_from("<qQ", b, off + k) for k in range(0, size, 16)]
        strtab_vaddr = next(v for t, v in entries if t == DT_STRTAB)
        # DT_STRTAB is a virtual address; map it back to a file offset via
        # the LOAD segment that contains it.
        strtab_off = None
        for i in range(e_phnum):
            p_type, _, p_offset, p_vaddr, _, p_filesz, _, _ = struct.unpack_from(
                "<IIQQQQQQ", b, e_phoff + i * e_phentsize)
            if p_type == PT_LOAD and p_vaddr <= strtab_vaddr < p_vaddr + p_filesz:
                strtab_off = strtab_vaddr - p_vaddr + p_offset
        for t, v in entries:
            if t == DT_NULL:
                break
            if t in (DT_NEEDED, DT_SONAME, DT_RUNPATH):
                tags.append((t, _cstr(b, strtab_off + v)))

    return {"min_align": min(aligns), "tags": tags, "exported": exported}


class ShibokenRecipe(PythonRecipe):
    version = "@PYSIDE_VERSION@"
    url = ("https://download.qt.io/official_releases/QtForPython/pyside6/"
           "PySide6-{version}-src/pyside-setup-everywhere-src-{version}.zip")
    # Of pyside-setup-everywhere-src-6.11.0.zip. A version bump must update it.
    sha512sum = ("866fa3e2b406cfc34b79cb766df433ba1066a6dc747bac4d0d93174482b88bed"
                 "03c1b6ba88f62eb24a74ecb521b1349863a3390ada8bd632b2233ebcbdb80f08")
    wheel_path = "@WHEEL_SHIBOKEN@"

    call_hostpython_via_targetpython = False
    install_in_hostpython = False

    #: The two files replaced: name in the wheel's shiboken6/ -> path in the
    #: CMake build tree.
    REBUILT = {
        "libshiboken6.abi3.so": "libshiboken/libshiboken6.abi3.so",
        "Shiboken.abi3.so": "Shiboken.abi3.so",
    }

    def build_arch(self, arch):
        site_packages = Path(self.ctx.get_python_install_dir(arch.arch))
        info(f"Installing {self.name} {self.version} from the wheel into {site_packages}")
        with zipfile.ZipFile(self.wheel_path) as wheel:
            wheel.extractall(site_packages)

        build_dir = Path(self.get_build_dir(arch.arch))
        built = self._cmake_build(arch, build_dir)

        pkg = site_packages / "shiboken6"
        for name, rel in self.REBUILT.items():
            new = built / rel
            self._check_against_original(pkg / name, new)
            shutil.copyfile(new, pkg / name)
            info(f"  replaced shiboken6/{name} with the 16 KB-aligned rebuild")

        shutil.copyfile(pkg / "libshiboken6.abi3.so",
                        Path(self.ctx.get_libs_dir(arch.arch)) / "libshiboken6.abi3.so")

    # --- the build --------------------------------------------------------

    def _cmake_build(self, arch, build_dir: Path) -> Path:
        host = os.environ.get("SHIBOKEN6_HOST_PATH", "")
        if not (Path(host) / "lib/cmake/Shiboken6Tools").is_dir():
            raise BuildInterruptingException(
                "SHIBOKEN6_HOST_PATH does not point at a host shiboken6 generator "
                f"({host!r}). It is exported by flake.nix's FHS shell; run the "
                "build from `nix develop --command mycu-android-build`.")

        python = self.ctx.python_recipe
        py_include = python.include_root(arch.arch)
        py_link = python.link_root(arch.arch)
        libpython = f"python{python.major_minor_version_string}"

        out = build_dir / "build-16k"
        shutil.rmtree(out, ignore_errors=True)
        out.mkdir()
        stub = self._write_qt6_stub(out)

        # Mirrors the linker flags of pyside-setup's own Android toolchain
        # template (tools/cross_compile_android/templates/
        # toolchain_default.tmpl.cmake), which is what produced the original:
        # the $ORIGIN runpaths, --as-needed, and an explicit -lpython — the
        # last is what gives the original its DT_NEEDED on libpython3.11.so.
        # Plus the one flag this recipe exists for.
        #
        # The single quotes around $ORIGIN are load-bearing: ninja runs the
        # link through `sh -c`, which would otherwise expand it to nothing and
        # leave a RUNPATH of ":/Qt/lib". _check_against_original catches that.
        ldflags = " ".join([
            f"-Wl,-z,max-page-size={PAGE_16K}",
            "-Wl,-O1", "-Wl,--hash-style=gnu",
            "-Wl,-rpath='$ORIGIN'", "-Wl,-rpath='$ORIGIN/Qt/lib'",
            "-Wl,--as-needed",
            f"-L{py_link}", f"-l{libpython}",
        ])

        env = dict(os.environ)
        env["PATH"] = self.get_recipe_env(arch)["PATH"] + ":" + env.get("PATH", "")

        with current_directory(str(out)):
            shprint(sh.cmake, "-G", "Ninja",
                    str(build_dir / "sources" / "shiboken6"),
                    f"-DCMAKE_TOOLCHAIN_FILE={self.ctx.ndk_dir}/build/cmake/android.toolchain.cmake",
                    f"-DANDROID_ABI={arch.arch}",
                    f"-DANDROID_PLATFORM=android-{TARGET_API}",
                    "-DANDROID_STL=c++_shared",
                    "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON",
                    "-DCMAKE_BUILD_TYPE=Release",
                    "-DCMAKE_CXX_FLAGS=-O2 -fomit-frame-pointer -DANDROID",
                    f"-DCMAKE_SHARED_LINKER_FLAGS={ldflags}",
                    f"-DCMAKE_MODULE_LINKER_FLAGS={ldflags}",
                    f"-DQFP_SHIBOKEN_HOST_PATH={host}",
                    # Runs libshiboken/embed/embedding_generator.py, a
                    # host-side step; any Python 3 will do.
                    f"-DQFP_PYTHON_HOST_PATH={sys.executable}",
                    f"-DQt6_DIR={stub}",
                    f"-DPython_INCLUDE_DIR={py_include}",
                    f"-DPython_LIBRARY={py_link}/lib{libpython}.so",
                    "-DPython_SOABI=cpython-311",
                    "-DFORCE_LIMITED_API=yes",
                    "-DBUILD_TESTS=OFF",
                    _env=env)
            shprint(sh.ninja, "libshiboken", "shibokenmodule", _env=env)
        return out

    @staticmethod
    def _write_qt6_stub(out: Path) -> Path:
        """A Qt6 CMake package that satisfies ShibokenSetup.cmake and no more.

        ShibokenSetup.cmake does `find_package(Qt6 REQUIRED COMPONENTS Core)`
        and compute_config_py_values() reads one property off Qt6::Core — a
        macOS deployment target. Neither libshiboken nor the Shiboken module
        links Qt, and the Android PySide6 wheel ships no CMake configs at all.
        """
        stub = out / "qt6-stub" / "Qt6"
        stub.mkdir(parents=True)
        (stub / "Qt6Config.cmake").write_text(
            "# Written by the cedarview shiboken6 recipe. See its docstring.\n"
            "set(Qt6_FOUND TRUE)\n"
            "set(Qt6Core_FOUND TRUE)\n"
            "set(Qt6_Core_FOUND TRUE)\n"
            "set(QT6_INSTALL_PREFIX \"/\")\n"
            "set(QT6_INSTALL_LIBS \"lib\")\n"
            "if(NOT TARGET Qt6::Core)\n"
            "    add_library(Qt6::Core INTERFACE IMPORTED)\n"
            "endif()\n")
        return stub

    @staticmethod
    def _check_against_original(original: Path, rebuilt: Path) -> None:
        old, new = elf_info(original), elf_info(rebuilt)
        problems = []
        if new["min_align"] < PAGE_16K:
            problems.append(f"LOAD alignment {new['min_align']:#x}, need {PAGE_16K:#x}")
        if new["tags"] != old["tags"]:
            problems.append(f"dynamic tags differ:\n    was {old['tags']}\n    now {new['tags']}")
        missing = sorted(old["exported"] - new["exported"])
        if missing:
            problems.append(f"{len(missing)} exported symbols missing, e.g. {missing[:5]}")
        if problems:
            raise BuildInterruptingException(
                f"the rebuilt {rebuilt.name} is not a drop-in replacement for "
                f"Qt's, so libpyside6 and the Qt bindings may not load against it:\n  "
                + "\n  ".join(problems))
        info(f"  {rebuilt.name}: align {new['min_align']:#x}, tags identical, "
             f"{len(old['exported'])}/{len(old['exported'])} exported symbols present")


recipe = ShibokenRecipe()
